#!/bin/bash
#
# chkconfig: 345 99 05
# description: Java deamon script
#
# A non-SUSE Linux start/stop script for Java daemons (SysV).
#
# Derived from -
# Home page: http://www.source-code.biz
# License:   GNU/LGPL (http://www.gnu.org/licenses/lgpl.html)
# Copyright 2006 Christian d'Heureuse, Inventec Informatik AG, Switzerland.
#
# History:
# 2014-12-12 Jordi Huguet: added classpath
# 2013-02-12 Jordi Huguet: For CTP service, when stopping service kill the children sub-processes spawned
# 2010-09-21 Josh Davis: Changed 'sudo' to 'su', fix some typos, removed unused variables
# 2009-03-04 Josh Davis: Ubuntu/Redhat version.
# 2006-06-27 Christian d'Heureuse: Script created.
# 2006-07-02 chdh: Minor improvements.
# 2006-07-10 chdh: Changes for SUSE 10.0.
 
 
# Set this to your Java installation
#JAVA_HOME=/usr/lib/jvm/java-6-sun/jre
#JAVA_HOME=/usr/lib/jvm/jre-1.6.0-openjdk.x86_64
JAVA_HOME=/opt/amc/devel/jdk-1.7.0
 
serviceNameLo="ctp"                                     # service name with the first letter in lowercase
serviceName="CTP"                                       # service name
serviceUser="ctp"                                       # OS user name for the service
serviceGroup="ctp"                                      # OS group name for the service
applDir="/xnat/ctp/bin"                                 # home directory of the service application
serviceUserHome="/xnat/$serviceUser"                    # home directory of the service user
serviceLogFile="/var/log/$serviceNameLo.log"            # log file for StdOut/StdErr
maxShutdownTime=5                                       # maximum number of seconds to wait for the daemon to terminate normally
pidFile="/var/run/$serviceNameLo.pid"                   # name of PID file (PID = process ID number)
javaCommand="java"                                      # name of the Java launcher without the path
javaExe="$JAVA_HOME/bin/$javaCommand"                   # file name of the Java application launcher executable
javaArgs="-jar $applDir/Runner.jar"                     # arguments for Java launcher
#
# Jordi - Set CLASSPATH for Advanced Imaging I/O Tools (JIO)
#
JIO_HOME=$applDir/libraries/jai_imageio-1_1/lib
JIO_CLASSPATH=$JIO_HOME/jai_imageio.jar:$JIO_HOME/clibwrapper_jiio.jar
#LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$JIOHOME
#javaCommandLine="$javaExe $javaArgs"                           # command line to start the Java service application
javaCommandLine="$javaExe -classpath $JIO_CLASSPATH $javaArgs"  # command line to start the Java service application
#
javaCommandLineKeyword="Runner.jar"                     # a keyword that occurs on the commandline, used to detect an already running service process and to distinguish it from others
 
# Makes the file $1 writable by the group $serviceGroup.
function makeFileWritable {
   local filename="$1"
   touch $filename || return 1
   chgrp $serviceGroup $filename || return 1
   chmod g+w $filename || return 1
   return 0; }
 
# Returns 0 if the process with PID $1 is running.
function checkProcessIsRunning {
   local pid="$1"
   if [ -z "$pid" -o "$pid" == " " ]; then return 1; fi
   if [ ! -e /proc/$pid ]; then return 1; fi
   return 0; }
 
# Returns 0 if the process with PID $1 is our Java service process.
function checkProcessIsOurService {
   local pid="$1"
   if [ "$(ps -p $pid --no-headers -o comm)" != "$javaCommand" ]; then return 1; fi
   grep -q --binary -F "$javaCommandLineKeyword" /proc/$pid/cmdline
   if [ $? -ne 0 ]; then return 1; fi
   return 0; }
 
# Returns 0 when the service is running and sets the variable $pid to the PID.
function getServicePID {
   if [ ! -f $pidFile ]; then return 1; fi
   pid="$(<$pidFile)"
   checkProcessIsRunning $pid || return 1
   checkProcessIsOurService $pid || return 1
   return 0; }
 
function startServiceProcess {
   cd $applDir || return 1
   rm -f $pidFile
   makeFileWritable $pidFile || return 1
   makeFileWritable $serviceLogFile || return 1
   cmd="nohup $javaCommandLine >>$serviceLogFile 2>&1 & echo \$! >$pidFile"
   su -m $serviceUser -s $SHELL -c "$cmd" || return 1
   sleep 0.1
   pid="$(<$pidFile)"
   if checkProcessIsRunning $pid; then :; else
      echo -ne "\n$serviceName start failed, see logfile."
      return 1
   fi
   return 0; }
 
function stopServiceProcess {
   #Jordi - issue: the PID recorded is the parent process but not the real one (sub-process) launched by Runner.jar
   #Jordi - solution: replace "kill & process ID" by "pkill & parent process ID", matching the child processes (SIGTERM signal)
   #kill -s TERM $pid || return 1
   pkill -TERM -P $pid || return 1
   for ((i=0; i<maxShutdownTime*10; i++)); do
      checkProcessIsRunning $pid
      if [ $? -ne 0 ]; then
         rm -f $pidFile
         return 0
         fi
      sleep 0.1
      done
   echo -e "\n$serviceName did not terminate within $maxShutdownTime seconds, sending SIGKILL..."
   #Jordi - solution: replace "kill & process ID" by "pkill & parent process ID", matching the child processes (SIGKILL signal)
   #kill -s KILL $pid || return 1
   pkill -KILL -P $pid || return 1
   local killWaitTime=15
   for ((i=0; i<killWaitTime*10; i++)); do
      checkProcessIsRunning $pid
      if [ $? -ne 0 ]; then
         rm -f $pidFile
         return 0
         fi
      sleep 0.1
      done
   echo "Error: $serviceName could not be stopped within $maxShutdownTime+$killWaitTime seconds!"
   return 1; }
 
function startService {
   getServicePID
   if [ $? -eq 0 ]; then echo "$serviceName is already running"; RETVAL=0; return 0; fi
   echo -n "Starting $serviceName...   "
   startServiceProcess
   if [ $? -ne 0 ]; then RETVAL=1; echo "failed"; return 1; fi
   echo "started PID=$pid"
   RETVAL=0
   return 0; }
 
function stopService {
   getServicePID
   if [ $? -ne 0 ]; then echo "$serviceName is not running"; RETVAL=0; return 0; fi
   echo -n "Stopping $serviceName...   "
   stopServiceProcess
   if [ $? -ne 0 ]; then RETVAL=1; echo "failed"; return 1; fi
   echo "stopped PID=$pid"
   RETVAL=0
   return 0; }
 
function checkServiceStatus {
   echo -n "Checking for $serviceName...   "
   if getServicePID; then
    echo "running PID=$pid"
    RETVAL=0
   else
    echo "stopped"
    RETVAL=3
   fi
   return 0; }
 
function main {
   RETVAL=0
   case "$1" in
      start)                                               # starts the Java program as a Linux service
         startService
         ;;
      stop)                                                # stops the Java program service
         stopService
         ;;
      restart)                                             # stops and restarts the service
         stopService && startService
         ;;
      status)                                              # displays the service status
         checkServiceStatus
         ;;
      *)
         echo "Usage: $0 {start|stop|restart|status}"
         exit 1
         ;;
      esac
   exit $RETVAL
}
 
main $1

